USE MAVENMOVIES;
-- Question 1: Retrieve the total number of rentals made in the Sakila database.
select count(*) from rental;


-- Question 2: Find the average rental duration (in days) of movies rented from the Sakila database.
select avg(datediff(return_date, rental_date)) as avg_day from rental;


-- Question 3:Display the first name and last name of customers in uppercase.
select upper( concat(first_name, " ", last_name)) as customer_name from customer;


-- Question 4:Extract the month from the rental date and display it alongside the rental ID.
select rental_id, month(rental_date) from rental;


-- Question 5: Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
select distinct customer_id, count(rental_id) from rental group by customer_id order by customer_id ;


-- Question 6: Find the total revenue generated by each store.
select store_id, sum(amount) from payment p
inner join staff s on p.staff_id = s.staff_id
group by store_id; 


-- Question 7: Display the title of the movie, customer s first name, and last name who rented it.


select title, Concat(first_name, " ", last_name) as customer_name from film 
inner join inventory on film.film_id = inventory.film_id
inner join rental on rental.inventory_id = inventory.inventory_id 
inner join customer on customer.customer_id = rental.customer_id
;


-- Question 8: Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
select concat(first_name, " ", last_name) as name from actor 
inner join film_actor on actor.actor_id = film_actor.actor_id
inner join film on film.film_id = film_actor.film_id
where title = 'Gone with the Wind'; 


-- GROUP BY:
-- Question 1: Determine the total number of rentals for each category of movies.


Select count(*),fc.category_id from rental r 
inner join inventory i on r.inventory_id = i.inventory_id
inner join film_category fc on fc.film_id = i.film_id 
group by fc.category_id;


-- Question 2:Find the average rental rate of movies in each language.
-- Hint: JOIN film and language tables, then use AVG () and GROUP BY.


select avg(rental_rate), language.language_id from film right join language on language.language_id = film.language_id group by language.language_id;




-- Question 3:Retrieve the customer names along with the total amount they've spent on rentals.
-- Hint: JOIN customer, payment, and rental tables, then use SUM() and GROUP BY.
select concat(first_name, " ", last_name) as customer_name, sum(amount) from customer 
inner join payment on customer.customer_id = payment.customer_id 
inner join rental on rental.rental_id = payment.rental_id
group by customer.customer_id;




-- Question 4: List the titles of movies rented by each customer in a particular city (e.g., 'London').
select title, concat(first_name, " ", last_name) as name , city from film 
inner join inventory on film.film_id = inventory.film_id
inner join rental on inventory.inventory_id = rental.inventory_id
inner join customer on customer.customer_id = rental.customer_id 
inner join address on customer.address_id = address.address_id 
inner join city on city.city_id = address.city_id;


-- Question 5: Display the top 5 rented movies along with the number of times they've been rented.
-- Hint: JOIN film, inventory, and rental tables, then use cOUNT() and GROUP BY, and limit the results.
select title, count(rental_duration) as no_of_film from film
inner join inventory on film.film_id = inventory.film_id
inner join rental on rental.inventory_id = inventory.inventory_id
group by film.film_id order by no_of_film desc limit 5;
